### PR TITLE
remove dataset_id_content from provider struct

### PR DESCRIPTION
**Pull request by goastler**
Removes dataset_id_content from provider as it is stored in the captcha data instead

### CODE REVIEW

**Comment by forgetso** [comment]
This makes the content verification slightly more complicated for the frontend. Previously, *captcha* (new name) would call `getProviderDetails` and get the `dataset_id_content` from that

https://github.com/prosopo/procaptcha/blob/6369fc578acf5747bca88c530d268e0149aeca2d/src/modules/ProsopoCaptchaApi.ts#L59-L83

Should `getRandomProvider` be changed to return the `dataset_content_id` ?

**Comment by goastler** [comment]
The logic behind this is that we're duplicating the storage of the dataset_content_id if it's in the CaptchaData and Provider struct. So to reduce contract storage, we could remove the field from the provider.

I think we have three options:
1. accept that we're duplicating a field a take the storage requirements hit
2. when calling getRandomActiveProvider(), make it return the provider _and_ the dataset_content_id
3. make the js side lookup the CaptchaData via the dataset_id to obtain the dataset_content_id

Currently, I believe option 2 would be best

**Comment by forgetso** [comment]
> Currently, I believe option 2 would be best

Agree, let's go with option 2

**Review by forgetso — DISMISSED** [review]

**Comment by goastler** [comment]
Sounds good, I'll add that in now so it's all in the same PR

**Review by forgetso — APPROVED** [review]

**Pull request merged**
